### ISSUE TITLE
Move per-route RBAC to OpenAPI via extensions

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/storyden#249]
as mentioned in #248 we can generate additional per-route middleware for each operation. Currently, RBAC is implemented by generating [this huge interface](https://github.com/Southclaws/storyden/blob/main/app/transports/http/bindings/openapi_rbac/openapi_rbac_gen.go) from which [the implementation](https://github.com/Southclaws/storyden/blob/main/app/transports/http/bindings/openapi_rbac/mapping.go) maps operations to either a permission, a rather obscure "this route is permissioned but it's implemented elsewhere due to ownership rules etc" and "no permission required".

This can be better expressed in OpenAPI:

```yaml
/threads:
  post:
    x-storyden-rbac:
      permission: CREATE_THREAD
  patch:
    x-storyden-rbac:
      permission: CUSTOM (?) # 
```

It could also make sense to include the permissions even of operations that aren't explicitly checked at the middleware layer but are checked later based on data queried (such as ownership)

```yaml
/threads:
  patch:
    x-storyden-rbac:
      permission: UPDATE_THREAD
      checked_internally: true # skips checking at middleware, assumes it will be checked at service layer
```
