### ISSUE TITLE
NGINX issue or may need help.

### ISSUE THREAD

**Issue by configari** [Southclaws/storyden#321]
I'm encountering an issue where the API works fine with the nginx configuration, but the web service throws a 502 Bad Gateway error, even though the web service is accessible on the host. Here's a breakdown of my setup:

1. **docker-compose.yml** file:
```yaml
version: '3.8'

services:
  storyden:
    image: ghcr.io/southclaws/storyden
    container_name: storyden
    environment:
      - PUBLIC_API_ADDRESS=https://api.example.com
      - PUBLIC_WEB_ADDRESS=https://example.com
      - SESSION_KEY=SESSIONKEY
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
```

2. **Nginx configuration for the web service**:
```nginx
server {
    server_name example.com;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name gco.revolt.ltd;

    listen 80;
    return 404; # managed by Certbot
}
```

3. **Nginx configuration for the API service**:
```nginx
server {
    server_name api.example.com;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name example.com;

    listen 80;
    return 404; # managed by Certbot
}
```

The **web service** is running on port 3000 and is accessible directly on the host, but when accessed via nginx, I get a 502 Bad Gateway error. On the other hand, the **API service** is working fine with its nginx configuration. Could you help me resolve the issue with the web service?
